name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 2.0.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  uni_map_platform_interface:
    git:
      url: https://github.com/EchoPuda/uni_map_platform_interface.git
  url_launcher: ^6.1.6
  foundation_fluttify:
    git:
      url: https://github.com/EchoPuda/foundation_fluttify.git
  core_location_fluttify:
    git:
      url: https://github.com/EchoPuda/core_location_fluttify.git
  amap_core_fluttify:
    git:
      url: https://github.com/EchoPuda/amap_core_fluttify.git
  amap_search_fluttify:
    git:
      url: https://github.com/EchoPuda/amap_search_fluttify.git
  amap_location_fluttify:
    git:
      url: https://github.com/EchoPuda/amap_location_fluttify.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin